### ISSUE TITLE
Output build ID

### ISSUE THREAD

**Issue by camnewnham** [RageAgainstThePixel/upload-meta-quest-build#11]
Occasionally the ovr platform util seems to get stuck on uploading symbols, but only when in combination with uploading a build. 
For us, it's useful to separate the two processes. To do this, we need to read the Build ID from the output of the `upload-quest-build` command and output it as a variable.

Currently we use powershell to do this which is fine but it would be cleaner if this action did so

For example:
```yaml
- name: Download OVR Platform Util
  shell: pwsh
  run: curl "https://www.oculus.com/download_app/?id=1076686279105243" -L -o ovr-platform-util.exe --silent

- name: Upload App Lab Build
  id: app_lab_upload
  shell: pwsh
  run: |
          & "./ovr-platform-util"  upload-quest-build <...> --disable-progress-bar | Tee-Object -Variable commandResult
          $regex = New-Object System.Text.RegularExpressions.Regex('(?<=Build ID: )[0-9]*') 
          if ($regex.IsMatch($commandResult)) { 
            $buildId = $regex.Match($commandResult)
            echo "Build ID is $buildId"
            echo "BUILD_ID=$($buildId)" >> $env:GITHUB_OUTPUT
          } else { 
            Write-Warning "Unable to find build ID in command output"
            echo $commandResult
          }

- name: Upload App Lab Symbols
  shell: pwsh
  run: "./ovr-platform-util upload-debug-symbols --parent ${{ steps.app_lab_upload.outputs.BUILD_ID }} <...> --debug-symbols-dir ./symbols_folder --debug-symbols-pattern *.so --disable-progress-bar"
```
